-- 멤버 테이블
CREATE TABLE MEMBER (
MEM_NUM NUMBER(10,0) PRIMARY KEY,
MEM_LEVEL NUMBER(3,0) DEFAULT 0,
MEM_NAME VARCHAR2(20) NOT NULL,
MEM_ID VARCHAR2(30) NOT NULL UNIQUE,
MEM_PWD VARCHAR2(30) NOT NULL,
MEM_GENDER VARCHAR2(3) NOT NULL,
MEM_ADDR VARCHAR2(200) NOT NULL,
MEM_TEL VARCHAR2(20),
MEM_BIRTH VARCHAR2(20) NOT NULL,
MEM_NICK VARCHAR2(30) NOT NULL UNIQUE,
MEM_EMAIL VARCHAR2(100)
);

--여행지 추천게시판
CREATE TABLE TRIP_BOARD(
TRIP_BOARD_NUM NUMBER(10,0) PRIMARY KEY,
TRIP_BOARD_TITLE VARCHAR2(100) NOT NULL,
TRIP_BOARD_CONT VARCHAR2(4000) NOT NULL,
TRIP_BOARD_CNT NUMBER(10,0),
TRIP_BOARD_DATE DATE DEFAULT SYSDATE,
TRIP_BOARD_LIKE NUMBER(10,0),
TRIP_BOARD_ADDR VARCHAR2(100) NOT NULL,
TRIP_BOARD_IMG1 VARCHAR2(200),
TRIP_BOARD_IMG2 VARCHAR2(200),
TRIP_BOARD_IMG3 VARCHAR2(200),
TRIP_BOARD_IMG4 VARCHAR2(200),
TRIP_BOARD_VIDEO1 VARCHAR2(300),
TRIP_BOARD_VIDEO2 VARCHAR2(300),
MEM_NUM NUMBER(10,0) ,
CONSTRAINT FK_MEM_NUM FOREIGN  KEY (MEM_NUM) REFERENCES MEMBER(MEM_NUM)
);

--자유게시판
CREATE TABLE FREE_BOARD(
FREE_BOARD_NUM NUMBER(10,0) PRIMARY KEY,
FREE_BOARD_TITLE VARCHAR2(100) NOT NULL,
FREE_BOARD_CONT VARCHAR2(4000) NOT NULL,
FREE_BOARD_CNT NUMBER(10,0),
FREE_BOARD_DATE DATE DEFAULT SYSDATE,
FREE_BOARD_LIKE NUMBER(10,0),
FREE_BOARD_IMG1 VARCHAR2(200),
FREE_BOARD_IMG2 VARCHAR2(200),
FREE_BOARD_IMG3 VARCHAR2(200),
FREE_BOARD_IMG4 VARCHAR2(200),
FREE_BOARD_VIDEO1 VARCHAR2(300),
FREE_BOARD_VIDEO2 VARCHAR2(300),
MEM_NUM NUMBER(10,0) NOT NULL,
CONSTRAINT FK_FREE_NUM FOREIGN  KEY (MEM_NUM) REFERENCES MEMBER(MEM_NUM)
);


--공지사항
CREATE TABLE NOTICE_BOARD(
NOTICE_BOARD_NUM NUMBER(10,0) PRIMARY KEY,
NOTICE_BOARD_TITLE VARCHAR2(100) NOT NULL,
NOTICE_BOARD_CONT VARCHAR2(4000) NOT NULL,
NOTICE_BOARD_CNT NUMBER(10,0),
NOTICE_BOARD_DATE DATE DEFAULT SYSDATE,
NOTICE_BOARD_IMG VARCHAR2(200),
NOTICE_BOARD_VIDEO VARCHAR2(300),
MEM_NUM NUMBER(10,0) NOT NULL,
CONSTRAINT FK_NOTICE_NUM FOREIGN  KEY (MEM_NUM) REFERENCES MEMBER(MEM_NUM)
);


--여행지 추천 게시판의 댓글
CREATE TABLE TRIP_RIPLE(
TRIP_RIPLE_NUM NUMBER(10,0) PRIMARY KEY,
TRIP_RIPLE_CONT VARCHAR2(300) NOT NULL,
TRIP_RIPLE_DATE DATE DEFAULT SYSDATE,
TRIP_BOARD_NUM NUMBER(10,0) NOT NULL,
CONSTRAINT FK_TRIP_BOARD_NUM FOREIGN  KEY (TRIP_BOARD_NUM) REFERENCES TRIP_BOARD(TRIP_BOARD_NUM)
);


--자유게시판의 댓글
CREATE TABLE FREE_RIPLE(
FREE_RIPLE_NUM NUMBER(10,0) PRIMARY KEY,
FREE_RIPLE_CONT VARCHAR2(300) NOT NULL,
FREE_RIPLE_DATE DATE DEFAULT SYSDATE,
FREE_BOARD_NUM NUMBER(10,0) NOT NULL,
CONSTRAINT FK_FREE_BOARD_NUM FOREIGN  KEY (FREE_BOARD_NUM) REFERENCES FREE_BOARD(FREE_BOARD_NUM)
);


--신고 테이블
CREATE TABLE REPORT(
REPORT_NUM NUMBER(10,0) PRIMARY KEY,
REPORT_CONT VARCHAR2(300) NOT NULL,
REPORT_DATE DATE DEFAULT SYSDATE,
REPORT_MEM NUMBER(10,0) NOT NULL, -- 신고 한 사람
REPORTED_MEM NUMBER(10,0) NOT NULL, -- 신고 당한 사람
CONSTRAINT FK_REPORT_MEM_NUM FOREIGN  KEY (REPORT_MEM) REFERENCES MEMBER(MEM_NUM),
CONSTRAINT FK_REPORTED_MEM_NUM FOREIGN  KEY (REPORTED_MEM) REFERENCES MEMBER(MEM_NUM)
);