create or replace PACKAGE BODY PKG_MENU AS

  PROCEDURE PROC_MENU_LIST(
IN_MENU_ID IN VARCHAR2,
O_CUR OUT SYS_REFCURSOR
) AS
  BEGIN
    OPEN O_CUR FOR
    SELECT MENU_ID, MENU_NAME, MENU_SEQ
    FROM MENUS
    ORDER BY MENU_SEQ;
    
  END PROC_MENU_LIST;

END PKG_MENU;