create or replace PACKAGE BODY PKG_MBOARD AS

  PROCEDURE PROC_MBOARD_LIST(
   IN_MENU_ID IN VARCHAR2,
   O_CUR OUT SYS_REFCURSOR
  ) AS
  
  BEGIN
    OPEN O_CUR FOR
    SELECT IDX, MENU_ID, TITLE, CONT, WRITER, REGDATE,
           READCOUNT, BNUM, LVL, STEP, NREF,DELNUM
    FROM MBOARD
    WHERE IN_MENU_ID = MENU_ID
    ORDER BY BNUM DESC;
           
  END PROC_MBOARD_LIST;
  
  
  

  PROCEDURE PROC_MBOARD_VIEW(
  IN_IDX IN NUMBER,
  O_CUR OUT SYS_REFCURSOR
  ) AS
  BEGIN
  
   UPDATE MBOARD 
   SET READCOUNT = READCOUNT + 1 
   WHERE IDX = IN_IDX;
   COMMIT;
  
    OPEN O_CUR FOR
    SELECT IDX, MENU_ID, TITLE, CONT, WRITER, REGDATE,
           READCOUNT, BNUM, LVL, STEP, NREF,DELNUM
    FROM MBOARD
    WHERE  IDX = IN_IDX;
    
  END PROC_MBOARD_VIEW;
  

  
  
  PROCEDURE PROC_MBOARD_INSERT(

       IN_MENU_ID    IN   VARCHAR2,
       IN_TITLE      IN   VARCHAR2,
       IN_CONT       IN   VARCHAR2,
       IN_WRITER     IN   VARCHAR2,
       IN_BNUM       IN   NUMBER,
       IN_LVL        IN   NUMBER,
       IN_STEP       IN   NUMBER,
       IN_NREF       IN   NUMBER
       ) AS
       V_IDX NUMBER(5,0);
  BEGIN
  
    SELECT NVL(MAX(IDX),0) + 1 
    INTO V_IDX
    FROM MBOARD;
  
    INSERT INTO MBOARD VALUES( 
       V_IDX,
       IN_MENU_ID,
       IN_TITLE,
       IN_CONT,
       IN_WRITER,
       SYSDATE,
       0,
       IN_BNUM,
       IN_LVL,
       IN_STEP,
       IN_NREF,
       0);
     COMMIT;
       
  END PROC_MBOARD_INSERT;


  
  
  PROCEDURE PROC_MBOARD_DELETE(
       IN_IDX IN NUMBER
       ) AS
  BEGIN
    DELETE FROM MBOARD WHERE IN_IDX = IDX;
    COMMIT;
    
  END PROC_MBOARD_DELETE;

  
  
  PROCEDURE PROC_MBOARD_UPDATE(
        IN_IDX IN NUMBER,
        IN_TITLE IN VARCHAR2,
        IN_CONT IN VARCHAR2
        ) AS
  BEGIN
  
   UPDATE MBOARD 
   SET TITLE = IN_TITLE, CONT = IN_CONT 
   WHERE IDX = IN_IDX;
     COMMIT;
   
  END PROC_MBOARD_UPDATE;

END PKG_MBOARD;